name: first_try_backfilling
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  font_awesome_flutter: ^9.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  charcode: ^1.2.0
  badges: ^2.0.1
  shimmer: ^2.0.0
  email_validator: ^2.0.1
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#132641"
  image: assets/icon.png
  android: true

flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/logo_foreground.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/

